package com.practica.controller.models.enumeration;

public enum Canton {
    ZAPOTILLO, PINDAL, PUYANGO, CELICA, MACARA, SOZORANGA, CHAGUARPAMBA, OLMEDO, 
    CALVAS, ESPINDOLA, QUILANGA, GONZANAMA, CATAMAYO, LOJA, SARAGURO, PALTAS;
}
